//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursachBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tolkunov_TheatreEntities : DbContext
    {
        public Tolkunov_TheatreEntities()
            : base("name=Tolkunov_TheatreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Актер> Актер { get; set; }
        public virtual DbSet<Афиша> Афиша { get; set; }
        public virtual DbSet<Билет> Билет { get; set; }
        public virtual DbSet<Пьеса> Пьеса { get; set; }
        public virtual DbSet<Роль> Роль { get; set; }
        public virtual DbSet<Сцена> Сцена { get; set; }
        public virtual DbSet<Театр> Театр { get; set; }
    }
}
