//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursachBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Афиша
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Афиша()
        {
            this.Сцена = new HashSet<Сцена>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Пьесы { get; set; }
        public string Место { get; set; }
        public Nullable<System.DateTime> ДатаВремя { get; set; }
    
        public virtual Пьеса Пьеса { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сцена> Сцена { get; set; }
    }
}
