//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursachBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Билет
    {
        public int ID { get; set; }
        public Nullable<int> ID_Пьесы { get; set; }
        public Nullable<int> Место { get; set; }
        public Nullable<System.DateTime> ДатаВремяПремьеры { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
        public Nullable<bool> Забронирован { get; set; }
        public Nullable<bool> Выкуплен { get; set; }
    
        public virtual Пьеса Пьеса { get; set; }
    }
}
