//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursachBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сцена
    {
        public int ID { get; set; }
        public string КоличествоМест { get; set; }
        public Nullable<int> ID_Театра { get; set; }
        public Nullable<int> ID_Афиши { get; set; }
    
        public virtual Афиша Афиша { get; set; }
        public virtual Театр Театр { get; set; }
    }
}
